#### Numpy
    * Numpy is core data science library for mathematics?scientific computing in python. It provides a high-performance multidimentional array object and foe working with array.
    * Numpy provides fast built-in object(nd-array).
    

In [1]:
import numpy as np

#### Numpy Array

In [2]:
arr = np.array([0,1,2,3,4,5,6,7])   # Create a rank 1 numpy array
display(arr)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
# array - int8, int16, int32, int64
arr.dtype # size in bits of each element from an array

dtype('int32')

In [5]:
arr.itemsize     #size of each element from an array

4

In [6]:
arr.shape  # shape returns a tuple listing length of the array along each dimensions


(8,)

In [7]:
print(arr.ndim)

1


In [8]:
print(arr.nbytes) # return number of bytes used by data of the n-d array


32


#### Array Operations
    * simple Array math operations.

In [9]:
a = np.array([10,20,30,40,50,60,70], dtype = 'int64')
b = np.array([1,2,3,4,5,6,7])

#velements by elements addition or subtraction
print(a + b)

[11 22 33 44 55 66 77]


In [10]:
print(a * b)

[ 10  40  90 160 250 360 490]


In [11]:
print(a ** b)

[           10           400         27000       2560000     312500000
   46656000000 8235430000000]


In [12]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1., 16.,2)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

In [15]:
import time
import numpy as np

array_size = 1000000
def python_version():
    #start time
    t1 = time.time()
    x = range(array_size)
    y = range(array_size)
    # Element by element addition
    z = [ x[i] + y[i] for i in range(len(x))]
    return time.time() - t1

def python_version():
    #start time
    t1 = time.time()
    x = np.arange(array_size)
    y = np.arange(array_size)
    z = [ x + y ]
    return time.time() - t1

t1 = python_version()
t2 = python_version()

print("numpy in this example is :" + str(t1/t2) + ' ' ,'Faster')
    

numpy in this example is :0.5641740883885061  Faster


In [16]:
print(t1, t2)

0.00400233268737793 0.007094144821166992


In [17]:
distance_list = [10,15,18,19,21,23]
time_list = [.20, .43, .55, 1.1, .59, 1.2]

speed = distance_list / time_list

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
distance_arr = np.array([10,15,18,19,21,23])
time_arr = [.20, .43, .55, 1.1, .59, 1.2]

speed_arr = distance_arr / time_arr
speed_arr

#### Types of Numpy Array

In [ ]:
# Create a 1-D Array
arr_1 = np.array([10,15,18,19,21,25])

In [ ]:
arr_2 = np.array([[1,5,8,9,11,15],[10,15,18,19,21,25]])
print(arr_2)

In [ ]:
arr_2.shape

In [ ]:
arr_2.dtype

In [ ]:
arr_2.ndim

In [ ]:
# row index = 1
arr_2[1][2]

In [ ]:
# indexing of 2-d Array
arr_2 [1][4]
# Alternative
arr_2 [-1][-2]

####        Three Dimentional Array

In [ ]:
arr_3 = np.array([[[0, 1,2,3,4,5],
                 [10,11,12,13,14,15],
                 [16,17,21, 32, 23, 19]],
                 
                 [[0, 1,2,3,4,5],
                 [10,11,12,13,14,15],
                 [16,17,21, 32, 23 ,19]],
                 
                 [[0, 1,2,3,4,5],
                 [10,11,12,13,14,15],
                 [16,17,21 ,32 ,23 ,19]]])


#### Numpy Array Sclicing

In [ ]:
arr_6 = np.arange(1, 37).reshape(6,6)
arr_6

In [ ]:
arr_4 = np.arange(50)
print(arr_4)


In [ ]:
arr_4 = arr_4[::-1]
arr_4

In [ ]:
arr_5 = np.arange(10)
print(arr_5)
reversed_arr = np.flipud(arr_5)
print(reversed_arr)

In [ ]:
arr_6 = np.arange(1, 37).reshape(6,6)
arr_6

In [ ]:
np.flipud(arr_6)

In [ ]:
np.fliplr(arr_6)

In [ ]:
np.flip(arr_6)


#### Array Create Function
     1. np.ones()
     2. np.zeros()

In [ ]:
# shape 3 rows & 6 columns

np.ones((3,6), dtype = 'float32')

In [ ]:
np.zeros((4,6), dtype = 'float32')

3. Identity Matrix
    * Generate a N x N Identity Matrix. The Default dtype is float64
    * Diagonal values are 1, non-diagonal are zeros.

In [ ]:
np.identity(7, dtype = 'int8')

4. Empty, Full, Fill

In [ ]:
arr_7 = np.empty(6)

In [ ]:
arr_7.fill(6.0)
arr_7

In [ ]:
# Create an array of shape 10, filled with 6.5

np.full(10, 6.5)

5. LinSpace
    * Generate N evenly spaced elements between start and stop(stop last value will be included)

In [ ]:
np.linspace(0,1,11)

In [ ]:
np.linspace(0,10,12).reshape(4,3)

6. logspace
  *Generate N evenly spaced elements on a log scale between start and stop(log base = 10)

In [ ]:
np.logspace(0, 1, 6, base=10)

#### Exercise 1: Create 2D Array with 1 on the Board & rest position will be zeros. shape = 10X10

In [ ]:
arr_8 = np.ones((10,10), dtype = 'int8')
arr_8 [1:-1,1:-1] = 0
arr_8

In [ ]:
arr_9 = np.zeros((10,10), dtype = 'int8')
arr_9[1:-1, 1:-1] = 1
arr_9


#### Exercise 2: Checker Board : Create 8x8 matrix & fill it with 1s & 0s in sequence 

In [ ]:
arr_10 = np.zeros((8,8), dtype = 'int8')
# Select every alternative element
arr_10[1::2, ::2] = 1
arr_10[::2, 1::2] = 1
print(arr_10)

In [ ]:
arr_10 = np.ones((8,8), dtype = 'int8')
# Select every alternative element
arr_10[::2, 1::2] = 0
arr_10[1::2,  ::2] = 0
print(arr_10)

#### Numpy 
   * Array Calcunation Method

In [ ]:
arr_11 = np.array([[[1, 2, 4],
                    [4, 5, 6]],
                   [[1, 2, 4],
                    [4,5,6]]])
arr_11

In [ ]:
arr_12 = np.arange(0, 36).reshape(6,6)
arr_12.min()

In [ ]:
arr_12

In [ ]:
arr_12.min(axis = 1)

In [ ]:
arr_12.min(axis = 0)

In [ ]:
# np.where() returns row index, column index
np.where(arr_12 > 20)

In [ ]:
np.where(arr_12 == arr_12.min())

In [ ]:
np.where(arr_12 == arr_12.min())[0][0], np.where(arr_12 == arr_12.min())[1][0]


#### Statistical Array Methods

In [ ]:
arr_1 = np.array([[[1, 2, 4],
                    [4, 5, 6]],
                   [[1, 2, 4],
                    [4,5,6]]])
arr_11

#### argmax()
   * Returns the index position of maximum value present in numpy array

In [18]:
arr_13 = [1.0, 2.0, 4.0, 5.0, 9.0, 3.0, 5.0, 1.0]
np.argmax(arr_13)

4

In [20]:
arr_13 = [0, 0, 0, 0, 0, 1, 0, 0, 0]
np.argmax(arr_13)

5